const dummyArticlesData = [
  {
    id: 1,
    title: 'Healthy Eating: Tips for a Balanced Diet',
    description: 'Lorem ipsum dolor sit amet...',
    content: 'Full content of article 1...',
    category: 'Health',
    date: '20 Maret 2024',
    imageUrl: '/assets/images/articlePlaceholder.png',
  },
  {
    id: 2,
    title: 'The Future of Technology: AI and Beyond',
    description: 'Maecenas sed diam eget risus varius...',
    content: 'Full content of article 2...',
    category: 'Technology',
    date: '15 Februari 2024',
    imageUrl: '/assets/images/articlePlaceholder.png',
  },
  {
    id: 3,
    title: 'Healthy Eating: Tips for a Balanced Diet',
    description: 'Lorem ipsum dolor sit amet...',
    content: 'Full content of article 1...',
    category: 'Health',
    date: '20 Maret 2024',
    imageUrl: '/assets/images/articlePlaceholder.png',
  },
  {
    id: 4,
    title: 'The Future of Technology: AI and Beyond',
    description: 'Maecenas sed diam eget risus varius...',
    content: 'Full content of article 2...',
    category: 'Technology',
    date: '15 Februari 2024',
    imageUrl: '/assets/images/articlePlaceholder.png',
  },
  {
    id: 5,
    title: 'Healthy Eating: Tips for a Balanced Diet',
    description: 'Lorem ipsum dolor sit amet...',
    content: 'Full content of article 1...',
    category: 'Health',
    date: '20 Maret 2024',
    imageUrl: '/assets/images/articlePlaceholder.png',
  },
  {
    id: 6,
    title: 'The Future of Technology: AI and Beyond',
    description: 'Maecenas sed diam eget risus varius...',
    content: 'Full content of article 2...',
    category: 'Technology',
    date: '15 Februari 2024',
    imageUrl: '/assets/images/articlePlaceholder.png',
  },
  {
    id: 7,
    title: 'Healthy Eating: Tips for a Balanced Diet',
    description: 'Lorem ipsum dolor sit amet...',
    content: 'Full content of article 1...',
    category: 'Health',
    date: '20 Maret 2024',
    imageUrl: '/assets/images/articlePlaceholder.png',
  },
  {
    id: 8,
    title: 'The Future of Technology: AI and Beyond',
    description: 'Maecenas sed diam eget risus varius...',
    content: 'Full content of article 2...',
    category: 'Technology',
    date: '15 Februari 2024',
    imageUrl: '/assets/images/articlePlaceholder.png',
  },
  {
    id: 9,
    title: 'Healthy Eating: Tips for a Balanced Diet',
    description: 'Lorem ipsum dolor sit amet...',
    content: 'Full content of article 1...',
    category: 'Health',
    date: '20 Maret 2024',
    imageUrl: '/assets/images/articlePlaceholder.png',
  },
  {
    id: 10,
    title: 'The Future of Technology: AI and Beyond',
    description: 'Maecenas sed diam eget risus varius...',
    content: 'Full content of article 2...',
    category: 'Technology',
    date: '15 Februari 2024',
    imageUrl: '/assets/images/articlePlaceholder.png',
  },
  {
    id: 11,
    title: 'Healthy Eating: Tips for a Balanced Diet',
    description: 'Lorem ipsum dolor sit amet...',
    content: 'Full content of article 1...',
    category: 'Health',
    date: '20 Maret 2024',
    imageUrl: '/assets/images/articlePlaceholder.png',
  },
  {
    id: 12,
    title: 'The Future of Technology: AI and Beyond',
    description: 'Maecenas sed diam eget risus varius...',
    content: 'Full content of article 2...',
    category: 'Technology',
    date: '15 Februari 2024',
    imageUrl: '/assets/images/articlePlaceholder.png',
  },
  {
    id: 13,
    title: 'Healthy Eating: Tips for a Balanced Diet',
    description: 'Lorem ipsum dolor sit amet...',
    content: 'Full content of article 1...',
    category: 'Health',
    date: '20 Maret 2024',
    imageUrl: '/assets/images/articlePlaceholder.png',
  },
  {
    id: 14,
    title: 'The Future of Technology: AI and Beyond',
    description: 'Maecenas sed diam eget risus varius...',
    content: 'Full content of article 2...',
    category: 'Technology',
    date: '15 Februari 2024',
    imageUrl: '/assets/images/articlePlaceholder.png',
  },
  {
    id: 15,
    title: 'Healthy Eating: Tips for a Balanced Diet',
    description: 'Lorem ipsum dolor sit amet...',
    content: 'Full content of article 1...',
    category: 'Health',
    date: '20 Maret 2024',
    imageUrl: '/assets/images/articlePlaceholder.png',
  },
  {
    id: 16,
    title: 'The Future of Technology: AI and Beyond',
    description: 'Maecenas sed diam eget risus varius...',
    content: 'Full content of article 2...',
    date: '20 Maret 2024',
    imageUrl: '/assets/images/articlePlaceholder.png',
  },
  {
    id: 17,
    title: 'Healthy Eating: Tips for a Balanced Diet',
    description: 'Lorem ipsum dolor sit amet...',
    content: 'Full content of article 1...',
    category: 'Health',
    date: '20 Maret 2024',
    imageUrl: '/assets/images/articlePlaceholder.png',
  },
  {
    id: 18,
    title: 'The Future of Technology: AI and Beyond',
    description: 'Maecenas sed diam eget risus varius...',
    content: 'Full content of article 2...',
    category: 'Technology',
    date: '15 Februari 2024',
    imageUrl: '/assets/images/articlePlaceholder.png',
  },
  {
    id: 19,
    title: 'The Future of Technology: AI and Beyond',
    description: 'Maecenas sed diam eget risus varius...',
    content: 'Full content of article 2...',
    category: 'Technology',
    date: '15 Februari 2024',
    imageUrl: '/assets/images/articlePlaceholder.png',
  },
];

export default dummyArticlesData;
